let accessToken="";
document.addEventListener("DOMContentLoaded",()=>{
 const form=document.getElementById("login-form");form.addEventListener("submit",login);document.getElementById("logout").onclick=()=>location.reload();
});
async function login(e){e.preventDefault();const msg=document.getElementById("login-msg");msg.textContent="Logging in…";
 try{const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email:email.value,password:password.value})});const s=await r.json();if(!r.ok)throw new Error("Login failed");accessToken=s.access_token;document.getElementById("login").style.display="none";document.getElementById("dashboard").style.display="block";loadOrders();}catch(err){msg.textContent="Invalid email or password.";}}
async function loadOrders(){const box=document.getElementById("orders");box.innerHTML='<div class="panel">Loading orders…</div>';try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/get_admin_orders`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"}});const orders=await r.json();if(!r.ok)throw new Error(JSON.stringify(orders));if(!orders.length){box.innerHTML='<div class="panel empty">No orders found.</div>';return;}box.innerHTML="";for(const o of orders){const card=document.createElement("div");card.className="panel admin-card";card.innerHTML=`<div class="admin-grid"><div><small>Order ID</small><strong>${o.id}</strong></div><div><small>Customer</small><strong>${o.customer_name}</strong></div><div><small>Total</small><strong>₹${o.total}</strong></div></div><p><strong>Phone:</strong> ${o.phone}</p><p><strong>Address:</strong> ${o.address}, ${o.city} - ${o.pin}</p><div class="order-items">Loading items…</div><p><strong>Status:</strong> <select class="status-select"><option>Pending</option><option>Confirmed</option><option>Shipped</option><option>Delivered</option><option>Cancelled</option></select> <button class="small-btn update">Update</button></p><small>${new Date(o.created_at).toLocaleString()}</small>`;card.querySelector(".status-select").value=o.status||"Pending";card.querySelector(".update").onclick=()=>updateStatus(o.id,card);box.appendChild(card);loadItems(o.id,card.querySelector(".order-items"));}}catch(e){box.innerHTML=`<div class="error">Unable to load orders.<br>${String(e.message).slice(0,300)}</div>`;}}
async function loadItems(id,box){try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/get_admin_order_items`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({p_order_id:id})});const items=await r.json();box.innerHTML=(items||[]).map(x=>`<div class="order-item"><span>${x.product_name} × ${x.quantity}</span><b>₹${x.unit_price}</b></div>`).join("")||"No products found.";}catch(e){box.textContent="Unable to load order items.";}}
async function updateStatus(id,card){const status=card.querySelector(".status-select").value;const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/update_order_status`,{method:"POST",headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({p_order_id:id,p_status:status})});if(!r.ok){alert("Status update failed.");return;}alert("Status updated.");}
